// Terms and privacy text, facts only. The operator, contact and sending services are placeholders
// until they are decided (see NEEDS_VERIFICATION.md). No claim here is about the municipality.

export const OPERATOR = '[Emri i organizatorit]';
export const OPERATOR_EN = '[Operator name]';
export const CONTACT = '[email i suportit]';
export const UPDATED = Date.UTC(2026, 9, 8);

type Section = { id?: string; h: string; p: string[] };

export const terms: Record<Lang, Section[]> = {
  sq: [
    { h: 'Çfarë është ky vend', p: ['Njësia 5 është një nismë e banorëve: një vend për të diskutuar problemet e Bllokut, Selitës dhe Tiranës së Re, për të propozuar zgjidhje dhe për të ndjekur takimet e ekipit të forumit. Nuk është faqe zyrtare e Bashkisë së Tiranës, nuk e zëvendëson Njësinë Administrative nr. 5 dhe as numrat e emergjencës.', 'Përdorimi është falas. Leximi nuk kërkon llogari; shkrimi, votimi, mbështetja e propozimeve dhe regjistrimi në takime kërkojnë llogari me email të konfirmuar me kod dhe të miratuar nga ekipi.'] },
    { h: 'Llogaria jote', p: ['Regjistrohu me emrin tënd të vërtetë dhe me të dhëna që të përkasin. Një person, një llogari. Mos krijo llogari për dikë tjetër dhe mos e ndaj fjalëkalimin.', 'Numri i celularit dhe rruga ku banon nuk u shfaqen kurrë banorëve të tjerë. I sheh vetëm ekipi, që të të njohë si fqinj para se ta miratojë llogarinë, dhe mund të të telefonojë për këtë. Ekipi nuk miraton llogari të dyfishta.'] },
    { h: 'Si sillemi me njëri-tjetrin', p: ['Nuk lejohen: fyerjet, kërcënimet dhe gjuha e urrejtjes; të dhënat private të të tjerëve (adresa, numra, foto pa leje); spami, reklama e fshehur dhe llogaritë e rreme; informacioni i rremë i paraqitur si fakt; çdo gjë që shkel ligjin ose të drejtat e autorit.'] },
    { h: 'Raportimet dhe moderimi', p: ['Çdo banor mund të raportojë një temë, koment, pyetje ose ngjarje. Raportimi është anonim: ekipi sheh raportimin, jo kush e dërgoi.', 'Kur tre banorë raportojnë të njëjtën gjë, ajo fshihet derisa ekipi të vendosë. Raportimet e përsëritura pa bazë nuk vlejnë më për fshehjen automatike, por i shkojnë gjithsesi ekipit.', 'Ekipi mund të heqë përmbajtje që shkel këto rregulla dhe, në raste të rënda ose të përsëritura, të pezullojë llogarinë. Çdo vendim ruhet: kush vendosi, çfarë dhe kur.'] },
    { h: 'Premtimi i ekipit', p: ['Ekipi i përgjigjet çdo teme dhe çdo propozimi brenda 24 orësh, dhe koha e përgjigjes shkruhet te tema. Propozimet tregojnë hapat e tyre (dorëzuar, në shqyrtim, planifikuar, realizuar ose refuzuar) me shpjegimin e çdo hapi.'] },
    { h: 'Ajo që shkruan mbetet e jotja', p: ['Temat, komentet dhe propozimet mbeten të tuat. Duke i publikuar, i lejon forumit t’i shfaqë brenda platformës dhe në faqet e saj publike.', 'Mund ta mbyllësh llogarinë kur të duash nga profili: nuk shkruan më dhe ajo që ke shkruar nuk shfaqet. Mund të kërkosh edhe fshirjen e plotë të të dhënave te suporti.'] },
    { h: 'Bizneset e lagjes', p: ['Disa karta janë shënuar “Sponsorizuar”: biznese të lagjes që mbështesin forumin. Mbështetja e tyre nuk ndikon kurrë te moderimi, te propozimet apo te ajo që shkruajnë banorët.'] },
    { h: 'Pa garanci', p: ['Forumi ofrohet ashtu siç është. Bëjmë të pamundurën që të jetë i disponueshëm dhe i saktë, por nuk premtojmë se nuk do të ndalet kurrë dhe nuk jemi përgjegjës për atë që shkruajnë banorët.'] },
    { id: 'kontakt', h: 'Ndryshimet dhe kontakti', p: [`Nëse këto rregulla ndryshojnë, data më sipër ndryshon dhe ndryshimet e rëndësishme njoftohen në forum. Përgjegjës për forumin: ${OPERATOR}. Pyetje dhe kërkesa: ${CONTACT}.`] },
  ],
  en: [
    { h: 'What this place is', p: ['Njësia 5 is a residents’ initiative: somewhere to discuss the problems of Blloku, Selita and Tirana e Re, propose solutions and follow the forum team’s meetings. It is not an official website of the Municipality of Tirana and does not replace Administrative Unit No. 5 or the emergency numbers.', 'It is free to use. Reading needs no account; writing, voting, supporting proposals and signing up for meetings need an account with an email confirmed by code and approved by the team.'] },
    { h: 'Your account', p: ['Sign up with your real name and details that belong to you. One person, one account. Don’t create an account for someone else and don’t share your password.', 'Your mobile number and the street you live on are never shown to other residents. Only the team sees them, to recognise you as a neighbour before approving the account, and it may call you for that. The team does not approve duplicate accounts.'] },
    { h: 'How we treat each other', p: ['Not allowed: insults, threats and hate speech; other people’s private details (addresses, numbers, photos without consent); spam, hidden advertising and fake accounts; false information presented as fact; anything that breaks the law or someone’s copyright.'] },
    { h: 'Reports and moderation', p: ['Any resident can report a topic, comment, question or event. Reporting is anonymous: the team sees the report, not who sent it.', 'When three residents report the same thing, it is hidden until the team decides. Repeated unfounded reports stop counting towards hiding, though they still reach the team.', 'The team may remove content that breaks these rules and, in serious or repeated cases, suspend an account. Every decision is kept: who decided, what and when.'] },
    { h: 'The team’s promise', p: ['The team replies to every topic and every proposal within 24 hours, and the reply time is shown on the topic. Proposals show their steps (submitted, under review, planned, delivered or rejected) with the explanation for each step.'] },
    { h: 'What you write stays yours', p: ['Your topics, comments and proposals remain yours. By publishing them you allow the forum to show them within the platform and on its public pages.', 'You can close your account at any time from your profile: you stop writing and what you wrote stops being shown. You can also ask support to delete your data completely.'] },
    { h: 'Neighbourhood businesses', p: ['Some cards are marked “Sponsored”: neighbourhood businesses that support the forum. Their support never affects moderation, proposals or what residents write.'] },
    { h: 'No guarantees', p: ['The forum is offered as it is. We do our best to keep it available and accurate, but we can’t promise it will never be down and we are not responsible for what residents write.'] },
    { id: 'kontakt', h: 'Changes and contact', p: [`If these rules change, the date above changes and important changes are announced in the forum. Responsible for the forum: ${OPERATOR_EN}. Questions and requests: ${CONTACT}.`] },
  ],
};

export const privacy: Record<Lang, Section[]> = {
  sq: [
    { h: 'Çfarë mbledhim', p: ['Vetëm atë që i duhet forumit për të punuar: emrin dhe mbiemrin (shfaqen te ajo që publikon); email-in (konfirmohet me një kod, shërben për hyrje dhe për ndryshimin e fjalëkalimit, nuk u shfaqet të tjerëve); numrin e celularit dhe rrugën ku banon (i sheh vetëm ekipi, që të të njohë para miratimit; me numrin mund edhe të hysh); lagjen, nëse e zgjedh; atë që shkruan dhe bën në forum: tema, komente, propozime, mbështetje, vota, regjistrime në takime dhe pyetje.'] },
    { h: 'Çfarë nuk mbledhim', p: ['Asnjë reklamë që të ndjek, asnjë Google Analytics, asnjë Facebook Pixel dhe asnjë gjurmues tjetër. Nuk i shesim kurrë të dhënat. Vendndodhja jote nuk lexohet kurrë nga telefoni.'] },
    { h: 'Cookies', p: ['Vetëm cookies teknike: seanca e hyrjes (që të mos hysh në çdo faqe) dhe një mesazh i shkurtër pas një veprimi (fshihet pas një minute). Zgjedhja “Ndalo animacionet” dhe një shënim se cilat karta biznesesh ke parë sot (që shikimet të mos numërohen dy herë) ruhen vetëm në shfletuesin tënd.'] },
    { h: 'Kush sheh çfarë', p: ['Banorët e tjerë shohin emrin tënd dhe atë që publikon. Votat në sondazhe nuk i tregohen askujt me emër; numërohen vetëm totalet. Ekipi sheh kush u regjistrua për një takim (që të dijë sa njerëz vijnë) dhe sheh përmbajtjen e raportuar; nuk sheh kush raportoi.', 'Ekipi teknik që mirëmban platformën mund të hyjë në bazën e të dhënave vetëm për mirëmbajtje.'] },
    { h: 'Shërbimet e të tjerëve', p: ['Faqja dhe të dhënat ruhen te Cloudflare. Email-et (kodet dhe lidhjet) dërgohen nga një shërbim që i përpunon vetëm për këtë qëllim. Nuk dërgojmë SMS. Nëse zgjedh “Vazhdo me Google”, Google të identifikon sipas kushteve të veta. Lidhjet e hartave te bizneset hapin Google Maps vetëm kur i klikon. Transmetimet live mund të shfaqen nga YouTube në modalitetin pa cookies.'] },
    { h: 'Sa kohë i ruajmë', p: ['Sa kohë ke llogari. Nëse e mbyll, përmbajtja jote nuk shfaqet më dhe mund ta rihapësh. Nëse kërkon fshirjen e plotë, i fshijmë të dhënat brenda 30 ditësh, përveç atyre që ligji na detyron të ruajmë.', 'Vendimet e moderimit ruhen si regjistër pa të dhënat e tua personale, që ekipi të shpjegojë pse u hoq diçka.'] },
    { h: 'Të drejtat e tua', p: [`Mund të shohësh të dhënat që kemi për ty, t’i korrigjosh, të kërkosh një kopje ose fshirjen e tyre. Shkruaj te ${CONTACT} dhe përgjigjemi brenda 30 ditësh. Përgjegjës për të dhënat: ${OPERATOR}.`, 'Nëse mendon se të dhënat e tua janë trajtuar keq, mund të ankohesh te Komisioneri për të Drejtën e Informimit dhe Mbrojtjen e të Dhënave Personale.'] },
    { h: 'Fëmijët', p: ['Forumi është për banorë 16 vjeç e lart. Nuk mbledhim me dije të dhëna të fëmijëve nën këtë moshë.'] },
  ],
  en: [
    { h: 'What we collect', p: ['Only what the forum needs to work: your first and last name (shown on what you publish); your email (confirmed with a code, used for signing in and resetting your password, never shown to others); your mobile number and the street you live on (seen only by the team, to recognise you before approval; you can also sign in with the number); your neighbourhood, if you choose one; what you write and do on the forum: topics, comments, proposals, support, votes, meeting sign-ups and questions.'] },
    { h: 'What we don’t collect', p: ['No advertising that follows you, no Google Analytics, no Facebook Pixel and no other trackers. We never sell data. Your location is never read from your phone.'] },
    { h: 'Cookies', p: ['Only technical cookies: your sign-in session (so you don’t sign in on every page) and a short message after an action (deleted after a minute). The “Stop animations” choice and a note of which business cards you have seen today (so views are not counted twice) are stored only in your browser.'] },
    { h: 'Who sees what', p: ['Other residents see your name and what you publish. Poll votes are not shown to anyone by name; only totals are counted. The team sees who signed up for a meeting (to know how many are coming) and sees reported content; it does not see who reported it.', 'The technical team that maintains the platform can reach the database for maintenance only.'] },
    { h: 'Other services', p: ['The site and its data are hosted by Cloudflare. Emails (codes and links) are sent by a service that processes them only for that purpose. We send no text messages. If you choose “Continue with Google”, Google identifies you under its own terms. Map links on businesses open Google Maps only when you click them. Live streams may be shown from YouTube in its no-cookie mode.'] },
    { h: 'How long we keep it', p: ['As long as you have an account. If you close it, your content is no longer shown and you can reopen it. If you ask for full deletion, we delete your data within 30 days, except what the law requires us to keep.', 'Moderation decisions are kept as a record without your personal details, so the team can explain why something was removed.'] },
    { h: 'Your rights', p: [`You can see the data we hold about you, correct it, ask for a copy or ask for its deletion. Write to ${CONTACT} and we answer within 30 days. Responsible for the data: ${OPERATOR_EN}.`, 'If you believe your data has been mishandled, you can complain to Albania’s Information and Data Protection Commissioner.'] },
    { h: 'Children', p: ['The forum is for residents aged 16 and over. We don’t knowingly collect data from children under that age.'] },
  ],
};
