// Compiles the Better Auth tables from the real auth config. migrations/0001_auth.sql came from
// this; it is already applied, so later auth columns (approvedAt, joinNote, ...) live in
// hand-written migrations (0003+). This now writes the full current schema to
// tools/.out/auth-schema.sql for comparison, never over a migration.
// Run: node tools/auth-sql.mjs   (Node 24 strips the TypeScript types of the imported config)
import { DatabaseSync } from 'node:sqlite';
import { mkdirSync, writeFileSync } from 'node:fs';
import { getMigrations } from 'better-auth/db/migration';
import { authOptions } from '../src/lib/auth-options.ts';

const options = authOptions({
  database: new DatabaseSync(':memory:'),
  baseURL: 'http://127.0.0.1:3750',
  secret: 'x'.repeat(32),
  sendMail: async () => {},
  sendSms: async () => {},
  sendCode: async () => {},
});
const { compileMigrations } = await getMigrations(options);
const sql = await compileMigrations();
mkdirSync('tools/.out', { recursive: true });
writeFileSync('tools/.out/auth-schema.sql', '-- Generated by tools/auth-sql.mjs from src/lib/auth-options.ts.\n' + sql.trim() + '\n');
console.log(sql);
